version: '3.8'

services:
  education-db:
    image: postgres:14
    container_name: education
    environment:
      POSTGRES_DB: education
      POSTGRES_USER: education
      POSTGRES_PASSWORD: test
    ports:
      - "5444:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U education" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      education-db:
        condition: service_healthy
    ports:
      - "8081:8081"